<?php


namespace App\Http\Controllers\Api;


use App\Events\InvitationAccepted;
use App\Events\InvitationCreated;
use App\Http\Controllers\Controller;
use App\Match;
use Illuminate\Http\Request;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 07/12/2019 - 19:33
 */
class MatchController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'invitee_id' => 'required|exists:users,id'
        ]);

        $match = new Match();
        $match->inviter()->associate($request->user());
        $match->invitee()->associate($request->input('invitee_id'));
        $match->save();

        event(new InvitationCreated($match->invitee, $match));

        return response()->json([
            'message' => 'Invitation Sent',
            'data' => $match->refresh()
        ]);
    }

    public function show(Match $match)
    {
        return response()->json([
            'data' => $match->load('inviter', 'invitee')
        ]);
    }

    /**
     * @param Request $request
     * @param Match $match
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function accept(Request $request, Match $match)
    {
        $this->validate($request, [
            'accept' => 'required|in:0,1'
        ]);

        $match->setAttribute('accepted', $request->input('accept'));
        $match->save();

        event(new InvitationAccepted($match));

        return response()->json([
            'message' => 'Invitation Accepted'
        ]);
    }
}
