<?php


namespace App\Listeners;


use App\Events\WinnerSelected;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 12/12/2019 - 16:18
 */
class UpdateUserStats
{

    /**
     * @var WinnerSelected
     */
    public $event;

    /**
     * UpdateUserStats constructor.
     * @param WinnerSelected $event
     */
    public function __construct(WinnerSelected $event)
    {
        $this->event = $event;
    }

    /**
     * Handle event
     */
    public function handle()
    {
        if ($this->event->match->getAttribute('winner_id') == $this->event->match->getAttribute('loser_id')) {
            $this->event->match->winner->incrementDraw();
            $this->event->match->winner->save();
            $this->event->match->loser->incrementDraw();
            $this->event->match->loser->save();
        } else {
            $this->event->match->winner->incrementWin();
            $this->event->match->winner->save();
            $this->event->match->loser->incrementLose();
            $this->event->match->loser->save();
        }
    }

}
