<?php


namespace App\Listeners;


use App\Events\WinnerSelected;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 12/12/2019 - 16:18
 */
class UpdateUserStats
{
    /**
     * Handle event
     * @param WinnerSelected $event
     */
    public function handle(WinnerSelected $event)
    {
        if ($event->match->getAttribute('winner_id') == $event->match->getAttribute('loser_id')) {
            $event->match->winner->increment('draw');
            $event->match->loser->increment('draw');
        } else {
            $event->match->winner->increment('win');
            $event->match->loser->increment('lose');
        }
    }

}
