<?php


namespace App\Events;


use App\Match;
use App\User;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Queue\SerializesModels;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 07/12/2019 - 19:35
 */
class InvitationCreated implements ShouldBroadcast
{
    use InteractsWithSockets, SerializesModels;

    public $match;

    public $user;

    public function __construct(User $user, Match $match)
    {
        $this->match = $match;
        $this->user = $user;
    }

    /**
     * @inheritDoc
     */
    public function broadcastOn()
    {
        return new PrivateChannel('invitations.' . $this->user->id);
    }
}
