<?php


namespace App\Events;


use App\Match;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Queue\SerializesModels;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 07/12/2019 - 19:39
 */
class InvitationAccepted implements ShouldBroadcast
{
    use SerializesModels;

    public $match;

    public function __construct(Match $match)
    {
        $this->match = $match;
    }

    /**
     * @inheritDoc
     */
    public function broadcastOn()
    {
        return new PrivateChannel('invitation_status.' . $this->match->id);
    }
}
