<?php


namespace App\Events;


use App\Match;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Queue\SerializesModels;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 11/12/2019 - 15:23
 */
class WinnerSelected implements ShouldBroadcast
{
    use SerializesModels;

    /**
     * @var Match
     */
    public $match;

    /**
     * WinnerSelected constructor.
     * @param Match $match
     */
    public function __construct(Match $match)
    {
        $this->match = $match;
    }

    /**
     * @inheritDoc
     */
    public function broadcastOn()
    {
        return new PrivateChannel('match.' . $this->match);
    }
}
