<?php


namespace App\Http\Controllers;


use App\Match;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 07/12/2019 - 20:09
 */
class MatchController extends Controller
{
    /**
     * MatchController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('lobby');
    }

    /**
     * @param Match $match
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Match $match)
    {
        return view('game', [
            'match' => $match
        ]);
    }

}
