<?php


namespace App\Http\Controllers;


use App\Match;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 07/12/2019 - 20:09
 */
class MatchController extends Controller
{
    public function __construct()
    {
        $this->middleware = 'auth';
    }

    public function index()
    {
        return view('lobby');
    }

    public function show(Match $match)
    {
        return view('game', [
            'match' => $match
        ]);
    }

}
