<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

/**
 * Auto generated by IntelliJ IDEA
 *
 * @author<rendy, rendyananta66@gmail.com>
 * at 13/12/2019 - 5:56
 */
class ProfileController extends Controller
{
    /**
     * ProfileController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit()
    {
        return view('profile.edit');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'email' => 'required|email',
            'password' => 'confirmed',
            'avatar' => 'image|dimensions:ratio=1'
        ]);

        $request->user()->name = $request->input('name');
        $request->user()->email = $request->input('email');

        if ($request->filled('password')) {
            $request->user()->password = bcrypt($request->input('password'));
        }

        if ($request->hasFile('avatar')) {
            if ($request->user()->getOriginal('avatar') !== null) {
                Storage::disk('public')->delete($request->user()->avatar);
            }

            $path = $request->file('avatar')->store('avatar', 'public');
            $request->user()->avatar = $path;
        }

        $request->user()->save();

        return redirect()->back();
    }

}
